config/routes.rb
Hairmo::Application.routes.draw do
  resources :cosmeticians
  resources :wanted_lists, only: [:new,:create,:destroy,:show,:edit,:update]
  resources :sessions, only: [:new,:create,:destroy]
  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'  

  match '/signup',  to:'cosmeticians#new'

  match '/signin',	to:'sessions#new'
  match '/signout', to:'sessions#destroy', via: :destroy

  match "/auth/:provider/callback" => "sessions#callback"
  match "/signout" => "sessions#destroy", :as => :logout

  match "/newpost" => "wanted_lists#new"
  match "/wanted_lists/:id" => "wanted_lists#show"
  match "/wanted_lists/:id/edit" => "wanted_lists#edit"

  match "/cosmeticians" => "cosmeticians#show"
  match "/cosmeticians_list" => "cosmeticians#all_cosmeticians"

end

app/models/area.rb
class Area < ActiveRecord::Base
  attr_accessible :name
end

app/models/cosmetician.rb
class Cosmetician < ActiveRecord::Base
  attr_accessible :area_id, :email, :name, :salon_address, :salon_name, :provider, :uid
  has_many :wanted_lists,dependent: :destroy

  #has_secure_password
  before_save {|cosmetician| cosmetician.email = email} #email.downcase
  before_save :create_remember_token

  def self.create_with_omniauth(auth)
	  create! do |cosmetician|
	  cosmetician.provider = auth["provider"]
	  cosmetician.uid = auth["uid"]
	  cosmetician.email = auth.info.email
	  cosmetician.image = auth.info.image
	  #cosmetician.password = auth["uid"]  #noztomcheck　これだめでしょ facebookからパスワード取れないから
		if cosmetician.provider == "facebook" 
		  cosmetician.name = auth["info"]["name"]
		else
		  cosmetician.name = auth["info"]["nickname"]
		end
	end
  end

  def feed 
	  WantedList.where("cosmetician_id = ?",id)
  end




  private
	def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
	end
end

app/models/wanted_list.rb
class WantedList < ActiveRecord::Base
  attr_accessible :cosmetician_id, :days, :hair_style, :memo, :name, :price, :sex
  belongs_to :cosmetician
  default_scope order: 'wanted_lists.created_at DESC'


  validates :cosmetician_id, presence:true
  validates :name,presence:true,length:{ maximum:15 }
  validates :hair_style,presence:true
  validates :price,presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  helper_method :current_cosmetician

  def handle_unverified_request
	  sign_out
	  super
  end

end

app/controllers/cosmeticians_controller.rb
class CosmeticiansController < ApplicationController
  before_filter :signed_in_cosmetician, only: [:index,:edit,:update,:destroy]
  before_filter :correct_cosmetician, only: [:edit,:update]
  before_filter :admin_cosmetician, only: :destroy

  def index
    @cosmeticians = Cosmetician.paginate(page: params[:page])
  end

  def all_cosmeticians
    @cosmeticians = Cosmetician.paginate(page: params[:page])
  end

  def new
    @cosmetician = Cosmetician.new
  end

  def show
    @cosmetician = current_cosmetician
	#@wanted_list = current_cosmetician.wanted_lists.build if signed_in?
	#@wanted_lists = @cosmetician.wanted_lists.paginate(page:params[:page])
	@item = WantedList.find_by_id(params[:id])
	@feed_items = current_cosmetician.feed.paginate(page:params[:page])
  end

  def create
    #facebook ?
    #auth = request.env["omniauth.auth"]
    @cosmetician = Cosmetician.new(params[:cosmetician]) #|| Cosmetician.create_with_omniauth(auth)
    if @cosmetician.save
      sign_in @cosmetician
      redirect_to @cosmetician
    else
      render 'new'
    end
    @cosmetician = Cosmetician.all
  end



  def edit
    @cosmetician = Cosmetician.find(params[:id])
  end

  def update
    @cosmetician = Cosmetician.find_by_id(params[:id])
    if @cosmetician.update_attributes(params[:cosmetician])
      sign_in @cosmetician
      redirect_to @cosmetician
    else
      render 'edit'
    end
  end

  def destroy
    Cosmetician.find(params[:id]).destroy
    redirect_to cosmeticians_url
  end

  def delete
  end

  private


  def correct_cosmetician
    @cosmetician = Cosmetician.find(params[:id])
    redirect_to(root_path) unless current_cosmetician?(@cosmetician)
  end

  def admin_cosmetician
    redirect_to(root_path) unless current_cosmetician.admin?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new 
	end

	#nomal login
	def create
		cosmetician =  Cosmetician.find_by_email(params[:session][:email])
		if cosmetician && cosmetician.authenticate(params[:session][:password]) 
			sign_in cosmetician
			redirect_back_or cosmetician
		else
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
    
	#facebook login 
	def callback
		auth = request.env["omniauth.auth"]
		cosmetician = Cosmetician.find_by_provider_and_uid(auth["provider"],auth["uid"]) 
		if cosmetician
			session[:cosmetician_id] = cosmetician.id
			sign_in cosmetician
			redirect_back_or cosmetician
		else
			Cosmetician.create_with_omniauth(auth)
			cosmetician = Cosmetician.find_by_provider_and_uid(auth["provider"],auth["uid"])
			if cosmetician
				sign_in cosmetician
				redirect_to cosmetician
			else
				redirect_to root_path
			end
		end
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
	  #@wanted_lists = WantedList.paginate(page: params[:page])
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/controllers/wanted_lists_controller.rb
class WantedListsController < ApplicationController
  before_filter :signed_in_cosmetician
  before_filter :correct_cosmetician, only: :destroy


  def index
  end



  def new
    @wanted_lists = WantedList.new
  end

  def show
    @wanted_lists = WantedList.find_by_id(params[:id])
	@item = current_cosmetician.wanted_lists.find_by_id(params[:id])
	@item = WantedList.find(params[:id])
	@cosmetician = current_cosmetician
  end


  def create
    @wanted_lists = current_cosmetician.wanted_lists.build(params[:wanted_list])
	cosmetician = current_cosmetician
    if @wanted_lists.save
      redirect_to cosmetician
    else
      render 'new'
    end
  end

  def edit
	  @wanted_list = WantedList.find(params[:id])
  end

  def update
	  @wanted_list = WantedList.find_by_id(params[:id])
	  if @wanted_list.update_attributes(params[:wanted_list])
		  redirect_to @wanted_list
	  else
		  render 'edit'
	  end
  end

  def destroy
	  @wanted_list.destroy
	  redirect_to root_path
  end


  private
  def correct_cosmetician
	  @wanted_list = current_cosmetician.wanted_lists.find_by_id(params[:id])
	  redirect_to root_url if @wanted_list.nil?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cosmeticians_helper.rb
module CosmeticiansHelper
	# 与えられたユーザーのGravatar (http://gravatar.com/) を返す。
#	def gravatar_for(user)
#		gravatar_id = Digest::MD5::hexdigest(user.email)#.downcase)
#	    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
#	    image_tag(gravatar_url, alt: user.name, class: "gravatar")
#	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(cosmetician)
		cookies.permanent[:remember_token] = cosmetician.remember_token
		self.current_cosmetician = cosmetician
	end

	def signed_in?
		!current_cosmetician.nil?
	end

	def sign_out
		self.current_cosmetician = nil
		cookies.delete(:remember_token)
	end

	def current_cosmetician=(cosmetician)
		@current_cosmetician = cosmetician
	end

	def current_cosmetician
		@current_cosmetician ||= Cosmetician.find_by_remember_token(cookies[:remember_token])
	end

	def current_cosmetician?(cosmetician)
		cosmetician == current_cosmetician
	end

	def signed_in_cosmetician
		unless signed_in?
			store_location
			redirect_to signin_url
		end
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to]||default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/wanted_lists_helper.rb
module WantedListsHelper
end

app/views/cosmeticians/_cosmetician.html.erb
<li>
<%= link_to cosmetician.name, cosmetician %>
<% if current_cosmetician.admin? && !current_cosmetician?(cosmetician) %>
	|<%= link_to "delete", cosmetician, method: :delete, data: {confirm: "You sure?"} %>
<% end %>
</li>

app/views/cosmeticians/_wantedlist.html.erb
<li>
<span class="name"><%= wanted_list.name %></span>
</li>

app/views/cosmeticians/all_cosmeticians.html.erb
<h1>ALL COSMETICIANS</h1>

<%= will_paginate %>
<ul>
	<%= render @cosmeticians %>
</ul>
<%= will_paginate %>

app/views/cosmeticians/delete.html.erb
<h1>Cosmeticians#delete</h1>
<p>Find me in app/views/cosmeticians/delete.html.erb</p>

app/views/cosmeticians/edit.html.erb
<h1>Cosmeticians#edit</h1>
<h2>update your profile</h2>

<div>
	<%= image_tag(@cosmetician.image) %>

	<%= form_for(@cosmetician) do |f| %>


		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :salon_name %>
		<%= f.text_field :salon_name %>

		<%= f.label :salon_address %>
		<%= f.text_field :salon_address %>

		<%= f.submit "Save Changes" %>
	<%end%>

	<a href="http://gravatar.com/emails">Change</a>
</div>

app/views/cosmeticians/index.html.erb
<h1>ALL COSMETICIANS</h1>

<%= will_paginate %>

<ul>
	<%= render @cosmeticians %>
</ul>

<%= will_paginate %>

app/views/cosmeticians/new.html.erb
<%= form_for(@cosmetician) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
<% end %>

app/views/cosmeticians/show.html.erb
<h1>Cosmeticians#show</h1>
<ul>
	<li><%= image_tag(@cosmetician.image) %></li>
	<li><%= @cosmetician.name %></li>
	<li><%= @cosmetician.email %></li>
	<li><%= @cosmetician.area_id%></li>
	<li><%= @cosmetician.salon_address %></li>
	<li><%= @cosmetician.salon_name %></li>
</ul>
<br/>
<br/>
<br/>

<% if signed_in? %>
	<div class="span8">
		<h3>WantedList</h3>
		<%= render 'shared/feed' %>
	</div>
<% end %>

app/views/layouts/_header.html.erb
<header>
<div>
	<ul>
		<li><%=link_to "Home",root_path %></li>
		<li><%=link_to "Help",help_path %></li>
		<% if signed_in? %>
			<li><%= link_to "Cosmeticians", cosmeticians_list_path %></li>
			<li>
				<%= link_to "My Page", current_cosmetician %>
				<ul>
					<li><%= link_to "Profile", current_cosmetician %></li>
					<li><%= link_to "Settings", edit_cosmetician_path(current_cosmetician) %></li>
					<li><%= link_to "new post", newpost_path %></li>
					<li>
						<%= link_to "Sign out", signout_path, method: "delete" %>
					</li>
				</ul>
			</li>
		<%else%>
			<li><%= link_to "Sign in", "/auth/facebook" %></li>
		<%end%>
	</ul>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE9]>
<script src="http://"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Hairmo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render'layouts/shim'%>
</head>
<body>
	<%= render'layouts/header'%>
	<div id="content">
		<%= yield %>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @wanted_lists.errors.any? %>
<div id="error_explanation">
 <div class="alert alert-error">
  The form contains <%= pluralize(@wanted_lists.errors.count, "error") %>.
 </div>
 <ul>
 <% @wanted_lists.errors.full_messages.each do |msg| %>
   <li>* <%= msg %></li>
 <% end %>
 </ul>
 </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol>
		<%= render partial: 'shared/feed_item', collection:@feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<%end%>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<span>
		<%= link_to feed_item.name, feed_item  %>
		<% if current_cosmetician?(feed_item.cosmetician) %>
			<%= link_to "delete", feed_item, method: :delete,
				data: { confirm: "You sure?" },
				title: feed_item.name %>
		<% end %>
	</span>
</li>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div>
	<h1>Home</h1>
	<% if signed_in? %>
	<% else%>
	<p>Hi! Sign up Now !!</p>
	<p>This Home Page is for first visited user</p>
	<ul>
		<li><%= link_to "facebookでlogin", "/auth/facebook" %></li>
		<!-- noztomcheck Twitter ログインは本番URLが必要なのでherokuに挙げた後-->
		<li><%= link_to "Twitterでログイン", "/auth/twitter" %></li>	
	<%end%>
</div>

app/views/wanted_lists/_wantedlist.html.erb
<li>
<span class="name"><%= @wanted_lists.name %></span>

<% if current_cosmetician?(wanted_list.cosmetician) %>
	<%= link_to "delete", wanted_list, method: :delete,
				data: { confirm: "You sure?" },
				title: wanted_list.name %>
<% end %>
</li>

app/views/wanted_lists/delete.html.erb
<h1>WantedLists#delete</h1>
<p>Find me in app/views/wanted_lists/delete.html.erb</p>

app/views/wanted_lists/edit.html.erb
<h1>WantedLists#edit</h1>
<p>Find me in app/views/wanted_lists/edit.html.erb</p>

app/views/wanted_lists/new.html.erb
<%= form_for @wanted_lists, :url => {:action => 'create'} do |f| %>
<%= render 'shared/error_messages' %>
<b>
<%= f.label :name %>
</b>
<br/>
<%= f.text_field :name %>
<br/>


<div class="field">
<b>
<%= f.label :days %>
</b>
<br/>
<%= f.text_field :days,:class => 'datepicker' %>
</div>
<br/>

<b>
<%= f.label :sex %>
</b>
<br/>
man
<%= f.radio_button 'sex', '0', {:checked => true} %>
woman
<%= f.radio_button 'sex', '1' %>
<br/>

<b>
<%= f.label :hair_style %>
</b>
<br/>
<%= f.select :hair_style,{"long" => "long","short" =>"short"}, :prompt => "Please select" %>
<br/>



<b>
<%= f.label :price %>
</b>
<br/>
<%= f.text_field :price %>
<br/>


<b>
<%= f.label :memo %>
</b>
<br/>
<%= f.text_field :memo %>
<br/>




<%= f.submit "Create my list", class: "btn btn-large btn-primary" %>
<% end %>

app/views/wanted_lists/show.html.erb
<h1>name <%= @wanted_lists.name %><br/></h1>
<ul>
	<li>days <%= @wanted_lists.days %></li>
	<li>sex
	<% if @wanted_lists.sex == true  %>
		woman
	<% else %>
		man
	<% end %></li>
	
	<li>hair_style <%= @wanted_lists.hair_style %></li>
	<li>price <%= @wanted_lists.price %></li>
	<li>memo <%= @wanted_lists.memo %></li>
</ul>

<br/>
<br/>
<br/>
<%= link_to 'Edit',edit_wanted_list_path %>
<br/>
<br/>

<h2><%= link_to 'To  My Pege', @cosmetician %></h2>